### PR TITLE
Add translations for Traditional Chinese (Hong Kong)

### PR DESCRIPTION
**Pull request by changanmoon**
This PR added translations for Traditional Chinese (Hong Kong) (`zh-HK`), and I've done all the translations in the Xcode String Catalog (empty strings are omitted).

However, some of the strings are unable to be translated right now because they are not listed. I have attached several screenshots here for your reference, note that untranslated parts are marked in red. 😃

Screenshot 1
Screenshot 2
Screenshot 3

If the issue is solved, I'll change this PR's status to "Ready for review".

### CODE REVIEW

**Comment by alienator88** [comment]
I just updated the 3rd screenshot for the Name/Size sorting strings.
The first 2 screenshots are happening because I'm using my own package that has certain functions built-in to it like the updater and permissions checker. It's not part of Pearcleaner directly, it's this: https://github.com/alienator88/AlinFoundation
I'm seeing if there's a way to get those strings into Pearcleaner directly.

**Comment by alienator88** [comment]
I'm in the process of manually adding these strings in, will have it updated shortly

**Comment by alienator88** [comment]
I had to make some updates to the AlinFoundation swift package, so you'll need to update that in your local project and pull my latest changes.
But I think I covered everything, let me know if you find anything else.
Thanks!

**Comment by changanmoon** [comment]
Thank you! I've found another two (in menubar and mini window mode):

Screenshot 4

Screenshot 5

**Comment by alienator88** [comment]
Ah nice catch. I'll get those updated tomorrow morning.
Thank you for the help!

**Comment by alienator88** [comment]
Just pushed, let me know if you see anything else. I feel like we're close 😂

**Comment by changanmoon** [comment]
Sounds great! I think it's time to make this PR ready for merging.

**Comment by alienator88** [comment]
I'll review and merge this tomorrow morning, thank you!

**Comment by alienator88** [comment]
Hi, would you be able to resolve the conflicts so I can merge?
Thanks!

**Comment by alienator88** [comment]
Not sure if this is needed anymore. As per the latest update in the translations issue https://github.com/alienator88/Pearcleaner/issues/83, looks like zh-HK has already been merged from another user.
Someone else was working on zh-Hans it looks like already and they'll possibly do zh-Hant as well.
Not sure if you want to just close this PR or..

**Comment by alienator88** [comment]
Ignore me, I'm losing my mind 😂 
Only zh-Hans has been merged so far. 
So zh-Hk in this PR is still needed once conflicts are resolved. Sorry!

**Comment by changanmoon** [comment]
Oh no, I accidentally closed this PR because I discarded all the changes.

Sorry for that... I'll create a new PR later.

**Pull request closed without merging**
