### PR TITLE
Add translations for Simplified Chinese

### PR DESCRIPTION
**Pull request by funsiyuan**
This PR simply adds Simplified Chinese translations. 
I used `Localizable.xcstrings` in Xcode to add the language translations.

The specific translation results are as follows.

image

image

image

image

### CODE REVIEW

**Comment by alienator88** [comment]
Awesome!
Just wanted to check one thing before merging.
Did you want to translate these 2 as well or does it make more sense to leave those in English?
https://github.com/alienator88/Pearcleaner/blob/61c824cf14eb4aa203c7e01a690f76f5341e9c55/Pearcleaner/Resources/Localizable.xcstrings#L4

https://github.com/alienator88/Pearcleaner/blob/61c824cf14eb4aa203c7e01a690f76f5341e9c55/Pearcleaner/Resources/Localizable.xcstrings#L7

The first one is in the About section of Settings next to the app version.
The 2nd one you can trigger to show up when you click on an app and then push CMD+B to show the condition builder.
image

**Comment by funsiyuan** [comment]
Thank you for your reply.

I believe these two sections should remain in English, so I intentionally didn’t translate them.

Besides that, for example, terms like ‘Version’ can also remain in English in my opinion.

image

**Comment by alienator88** [comment]
Sounds good!
If you're all done, let me know and I can merge this tomorrow.

**Comment by funsiyuan** [comment]
@alienator88 
Hello, I think I’m ready now.
You can merge this PR at any time.

**Pull request merged**
